package dnsutil

const (
	// OPCODE
	DNS_OPCODE_QUERY  = uint8(0)
	DNS_OPCODE_IQUERY = uint8(1) // inverse query
	DNS_OPCODE_STATUS = uint8(2)
	DNS_OPCODE_NOTIFY = uint8(4)
	DNS_OPCODE_UPDATE = uint8(5)
	DNS_OPCODE_DSO    = uint8(6)

	// QR
	DNS_QR_REQUEST  = 0
	DNS_QR_RESPONSE = 1

	// TYPE
	DNS_TYPE_INT_A     = 1
	DNS_TYPE_INT_NS    = 2
	DNS_TYPE_INT_CNAME = 5
	DNS_TYPE_INT_SOA   = 6
	DNS_TYPE_INT_PTR   = 12
	DNS_TYPE_INT_MX    = 15
	DNS_TYPE_INT_TXT   = 16
	DNS_TYPE_INT_AAAA  = 28
	DNS_TYPE_INT_SRV   = 33
	DNS_TYPE_INT_ANY   = 255

	// TYPE
	DNS_TYPE_STR_A     = "A"
	DNS_TYPE_STR_NS    = "NS"
	DNS_TYPE_STR_CNAME = "CNAME"
	DNS_TYPE_STR_SOA   = "SOA"
	DNS_TYPE_STR_PTR   = "PTR"
	DNS_TYPE_STR_MX    = "MX"
	DNS_TYPE_STR_TXT   = "TXT"
	DNS_TYPE_STR_AAAA  = "AAAA"
	DNS_TYPE_STR_SRV   = "SRV"
	DNS_TYPE_STR_ANY   = "ANY"

	// CLASS
	DNS_CLASS_INT_IN   = 1
	DNS_CLASS_INT_NONE = 254
	DNS_CLASS_INT_ANY  = 255

	DNS_CLASS_STR_IN   = "IN"
	DNS_CLASS_STR_NONE = "NONE"
	DNS_CLASS_STR_ANY  = "ANY"

	// RCODE
	DNS_RCODE_NOERROR   = uint8(0)
	DNS_RCODE_FORMERR   = uint8(1)
	DNS_RCODE_SERVFAIL  = uint8(2)
	DNS_RCODE_NOTIMP    = uint8(4)
	DNS_RCODE_REFUSED   = uint8(5)
	DNS_RCODE_YXDOMAIN  = uint8(6)
	DNS_RCODE_YXRRSET   = uint8(7)
	DNS_RCODE_NXRRSET   = uint8(8)
	DNS_RCODE_NOTAUTH   = uint8(9)
	DNS_RCODE_NOTZONE   = uint8(10)
	DNS_RCODE_DSOTYPENI = uint8(11)

	// for del, when del rr, type is ANY, not the initially set value;
	// so ,use rrDelKey to remember this key
	DNS_RR_DEL_KEY = "DEL"

	DNS_DOMAIN_COMPRESSION_POINTER = uint16(0xc000)
	DNS_DOMAIN_ONE_LABEL_MAXLENGTH = uint8(63) // <=63
)

var DnsRCodes map[uint8]string = map[uint8]string{
	DNS_RCODE_NOERROR:   "NoError",
	DNS_RCODE_FORMERR:   "FormErr",
	DNS_RCODE_SERVFAIL:  "ServFail",
	DNS_RCODE_NOTIMP:    "NotImp",
	DNS_RCODE_REFUSED:   "Refused",
	DNS_RCODE_YXDOMAIN:  "YXDomain",
	DNS_RCODE_YXRRSET:   "YXRRSet",
	DNS_RCODE_NXRRSET:   "NXRRSet",
	DNS_RCODE_NOTAUTH:   "NotAuth",
	DNS_RCODE_NOTZONE:   "NotZone",
	DNS_RCODE_DSOTYPENI: "DsoTypeNotImp",
}

var DnsIntTypes map[uint16]string = map[uint16]string{
	DNS_TYPE_INT_A:     DNS_TYPE_STR_A,
	DNS_TYPE_INT_NS:    DNS_TYPE_STR_NS,
	DNS_TYPE_INT_CNAME: DNS_TYPE_STR_CNAME,
	DNS_TYPE_INT_SOA:   DNS_TYPE_STR_SOA,
	DNS_TYPE_INT_PTR:   DNS_TYPE_STR_PTR,
	DNS_TYPE_INT_MX:    DNS_TYPE_STR_MX,
	DNS_TYPE_INT_TXT:   DNS_TYPE_STR_TXT,
	DNS_TYPE_INT_AAAA:  DNS_TYPE_STR_AAAA,
	DNS_TYPE_INT_SRV:   DNS_TYPE_STR_SRV,
	DNS_TYPE_INT_ANY:   DNS_TYPE_STR_ANY,
}
var DnsStrTypes map[string]uint16 = map[string]uint16{
	DNS_TYPE_STR_A:     DNS_TYPE_INT_A,
	DNS_TYPE_STR_NS:    DNS_TYPE_INT_NS,
	DNS_TYPE_STR_CNAME: DNS_TYPE_INT_CNAME,
	DNS_TYPE_STR_SOA:   DNS_TYPE_INT_SOA,
	DNS_TYPE_STR_PTR:   DNS_TYPE_INT_PTR,
	DNS_TYPE_STR_MX:    DNS_TYPE_INT_MX,
	DNS_TYPE_STR_TXT:   DNS_TYPE_INT_TXT,
	DNS_TYPE_STR_AAAA:  DNS_TYPE_INT_AAAA,
	DNS_TYPE_STR_SRV:   DNS_TYPE_INT_SRV,
	DNS_TYPE_STR_ANY:   DNS_TYPE_INT_ANY,
}

var DnsIntClasses map[uint16]string = map[uint16]string{
	DNS_CLASS_INT_IN:   DNS_CLASS_STR_IN,
	DNS_CLASS_INT_NONE: DNS_CLASS_STR_NONE,
	DNS_CLASS_INT_ANY:  DNS_CLASS_STR_ANY,
}
var DnsStrClasses map[string]uint16 = map[string]uint16{
	DNS_CLASS_STR_IN:   DNS_CLASS_INT_IN,
	DNS_CLASS_STR_NONE: DNS_CLASS_INT_NONE,
	DNS_TYPE_STR_ANY:   DNS_CLASS_INT_ANY,
}
