package dnsutil

const (
	// OPCODE
	DNS_OPCODE_UPDATE = 5
	DNS_OPCODE_DSO    = 6

	// QR
	DNS_QR_REQUEST  = 0
	DNS_QR_RESPONSE = 1

	// TYPE
	DNS_TYPE_INT_A     = 1
	DNS_TYPE_INT_NS    = 2
	DNS_TYPE_INT_CNAME = 5
	DNS_TYPE_INT_SOA   = 6
	DNS_TYPE_INT_PTR   = 12
	DNS_TYPE_INT_MX    = 15
	DNS_TYPE_INT_TXT   = 16
	DNS_TYPE_INT_AAAA  = 28
	DNS_TYPE_INT_SRV   = 33
	DNS_TYPE_INT_ANY   = 255

	// TYPE
	DNS_TYPE_STR_A     = "A"
	DNS_TYPE_STR_NS    = "NS"
	DNS_TYPE_STR_CNAME = "CNAME"
	DNS_TYPE_STR_SOA   = "SOA"
	DNS_TYPE_STR_PTR   = "PTR"
	DNS_TYPE_STR_MX    = "MX"
	DNS_TYPE_STR_TXT   = "TXT"
	DNS_TYPE_STR_AAAA  = "AAAA"
	DNS_TYPE_STR_SRV   = "SRV"
	DNS_TYPE_STR_ANY   = "ANY"

	// CLASS
	DNS_CLASS_INT_IN   = 1
	DNS_CLASS_INT_NONE = 254
	DNS_CLASS_INT_ANY  = 255

	DNS_CLASS_STR_IN   = "IN"
	DNS_CLASS_STR_NONE = "NONE"
	DNS_CLASS_STR_ANY  = "ANY"

	// RCODE
	DNS_RCODE_NOERROR   = 0
	DNS_RCODE_FORMERR   = 1
	DNS_RCODE_SERVFAIL  = 2
	DNS_RCODE_NOTIMP    = 4
	DNS_RCODE_REFUSED   = 5
	DNS_RCODE_YXDOMAIN  = 6
	DNS_RCODE_YXRRSET   = 7
	DNS_RCODE_NXRRSET   = 8
	DNS_RCODE_NOTAUTH   = 9
	DNS_RCODE_NOTZONE   = 10
	DNS_RCODE_DSOTYPENI = 11

	// for del, when del rr, type is ANY, not the initially set value;
	// so ,use rrDelKey to remember this key
	DNS_RR_DEL_KEY = "DEL"
)

var DnsIntTypes map[uint16]string = map[uint16]string{
	DNS_TYPE_INT_A:     DNS_TYPE_STR_A,
	DNS_TYPE_INT_NS:    DNS_TYPE_STR_NS,
	DNS_TYPE_INT_CNAME: DNS_TYPE_STR_CNAME,
	DNS_TYPE_INT_SOA:   DNS_TYPE_STR_SOA,
	DNS_TYPE_INT_PTR:   DNS_TYPE_STR_PTR,
	DNS_TYPE_INT_MX:    DNS_TYPE_STR_MX,
	DNS_TYPE_INT_TXT:   DNS_TYPE_STR_TXT,
	DNS_TYPE_INT_AAAA:  DNS_TYPE_STR_AAAA,
	DNS_TYPE_INT_SRV:   DNS_TYPE_STR_SRV,
	DNS_TYPE_INT_ANY:   DNS_TYPE_STR_ANY,
}
var DnsStrTypes map[string]uint16 = map[string]uint16{
	DNS_TYPE_STR_A:     DNS_TYPE_INT_A,
	DNS_TYPE_STR_NS:    DNS_TYPE_INT_NS,
	DNS_TYPE_STR_CNAME: DNS_TYPE_INT_CNAME,
	DNS_TYPE_STR_SOA:   DNS_TYPE_INT_SOA,
	DNS_TYPE_STR_PTR:   DNS_TYPE_INT_PTR,
	DNS_TYPE_STR_MX:    DNS_TYPE_INT_MX,
	DNS_TYPE_STR_TXT:   DNS_TYPE_INT_TXT,
	DNS_TYPE_STR_AAAA:  DNS_TYPE_INT_AAAA,
	DNS_TYPE_STR_SRV:   DNS_TYPE_INT_SRV,
	DNS_TYPE_STR_ANY:   DNS_TYPE_INT_ANY,
}

var DnsIntClasses map[uint16]string = map[uint16]string{
	DNS_CLASS_INT_IN:   DNS_CLASS_STR_IN,
	DNS_CLASS_INT_NONE: DNS_CLASS_STR_NONE,
	DNS_CLASS_INT_ANY:  DNS_CLASS_STR_ANY,
}
var DnsStrClasses map[string]uint16 = map[string]uint16{
	DNS_CLASS_STR_IN:   DNS_CLASS_INT_IN,
	DNS_CLASS_STR_NONE: DNS_CLASS_INT_NONE,
	DNS_TYPE_STR_ANY:   DNS_CLASS_INT_ANY,
}
